name: CI_action

on:
  pull_request:
    types: [closed]

jobs:
  build:

    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run the tests
      working-directory: ./frontend
      run: npm test

    - name: Build
      working-directory: ./frontend
      run: npm run build
